/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface TemplateTagIssue {
    'container': HTMLElement;
  }
  interface TemplateTagIssueAttributes extends StencilHTMLAttributes {
    'container'?: HTMLElement;
  }
}

declare global {
  interface StencilElementInterfaces {
    'TemplateTagIssue': Components.TemplateTagIssue;
  }

  interface StencilIntrinsicElements {
    'template-tag-issue': Components.TemplateTagIssueAttributes;
  }


  interface HTMLTemplateTagIssueElement extends Components.TemplateTagIssue, HTMLStencilElement {}
  var HTMLTemplateTagIssueElement: {
    prototype: HTMLTemplateTagIssueElement;
    new (): HTMLTemplateTagIssueElement;
  };

  interface HTMLElementTagNameMap {
    'template-tag-issue': HTMLTemplateTagIssueElement
  }

  interface ElementTagNameMap {
    'template-tag-issue': HTMLTemplateTagIssueElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
